### ISSUE TITLE
OM Tracker - handling multiple migrations

### ISSUE THREAD

**Issue by LoganLaFollette** [tsgrp/OpenMigrate#18]
If a client has the need to track multiple migrations, the OM tracker can be set up as an individual war (one per migration) on a tomcat to connect and track individual migrations. However, the configuration data is saved via localStorage so multiple wars within the same domain overwrite each other's configuration.  The suggested solution to this would be to: 
- have an injectable app ID to be injected into the MigrationTracker bean in OM, then pass that app ID back to the tracker with every REST call. 
- have the tracker store the information in local storage based on the app ID

**Comment by sambelcher1** [comment]
closed with commit 17090

MULTIPLE MIGRATION TRACKING: Added the ability to track multiple different migrations. On each page there is now a drop down in the header that contains any available migrations that have been set up in the settings tab. No data will load until one of those migrations are selected. Once one is selected it will start to track that migration just like normal. Whenever a migration is switched then it will clear out any stats and load new ones for the newly selected migration. In the settings tab there is now the ability to add/delete migrations that have already been set up.

CR: rsaladrigas, tparzgnat, rvishweshwar
