### ISSUE TITLE
OM Solr Cloud Enhancements

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/OpenMigrate#33]
## Overview
- Updating the OM Solr module to use Solr APIs, which can be used to publish to the Solr Cloud via zookeeper. 
- With this updates, there is no longer a need for the `tsgrpSolr` jar since we are calling the Solr APIs within the OM Solr module now.
- Some jars are removed from the OM Solr module `build.gradle` as they are no longer needed.
- The ability to configure what Solr version at a project level. This is important because this Solr version that OM is built with has to match the Solr where it will commit documents.

**Comment by mwojno-tsg** [comment]
Closed with commit: **18690**

The commit removes the need for the tsgrp solr jar. It also adds the following functionality and changes:
- A solr connector is used in all relevant areas to initialize the solr client now. Instead of simply only putting the solr url, we will inject a solr connector. This lets us have the ability to configure solr cloud or solr url (http).
- The solr version is made configurable in the project's build.gradle. This is to make sure the solr that OM is built with is the same that it will be committing to or else an error could be thrown.
- A sample file system to solr was added with examples of the solr cloud enhancements and how to wire up either bean correctly.
- The sample and edge4 projects were updated with examples of the solr cloud enhancement beans and properties that need to be set.

CR: rsaladrigas, tparzgnat

**Comment by renesaladrigas** [comment]
SOLR CLOUD TIKA UPGRADE: The recent addition of Solr cloud integration in revision 18690 was not indexing full text search onto Solr. Given the changes in API, Solr no longer performs the extraction of content for full text indexing, OpenMigrate is responsible for that via the tika dependency. The version of tika OM was using was too old to index full text content, so this bump up to 1.21 (and related dependencies of tika) allow for full text indexing. Note that this is applicable to Solr version 8.8.1 (what has been defaulted in the javadocs project), and other versions of Solr might need a different set of dependencies (something that needs to be addressed with project level variables to follow suit with Solr, or changing the solrj dependencies to be transitive and override other dependencies found on the core module).

CR: aking, mwojno, tparzgnat
