### ISSUE TITLE
Enhance all listeners to use a "criteriaAttr" and "criteriaRegex"

### ISSUE THREAD

**Issue by renesaladrigas** [tsgrp/OpenMigrate#6]
Currently there are some listeners that implement a "criteriaAttr" and a "criteriaRegex" injectable that allows the listener to use an attribute on the node and a supplied value to determine if the listener should be executed or not.

If possible, it would be great to implement this in the interfaces or abstract listener classes so that all listeners can have access to tools that determine on a node per node basis if this listener should be executed or not.

**Comment by parzgnat** [comment]
Completed by @RudraVishweshwar
